### PR TITLE
Add Bang & Olufsen React Suspense demo

### PR DESCRIPTION
**Pull request by stipsan**
The talk was done back in september so while the talk itself is outdated by now (simple-cache-provider is now react-cache etc) the code has been updated to a fresh checkout of react master today 😄

### CODE REVIEW

**Comment by luisherranz** [comment]
The site doesn't seem to be working, I get "failed to fetch dynamic module" errors when clicking on a speaker: https://bang-olufsen-react-suspense-demo.now.sh/

**Comment by sw-yx** [comment]
thanks :)

**Comment by stipsan** [comment]
@luisherranz interesting, can you tell me what browser you are using? Or better yet your user agent string.
I am using the new dynamic import syntax to load modules. Not every browser that supports esm supports dynamic imports so I am checking the user agent and comparing to the caniuse api. If the browser isn’t whitelisted it should fall back to using SystemJS.

**Comment by luisherranz** [comment]
Chrome 69 un Android 8, but seems to be working now.

**Pull request merged**
